DROP TABLE IF EXISTS `CAMPO`;
CREATE TABLE IF NOT EXISTS `CAMPO` (
  `ID` tinyint(4) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `INDIRIZZO` varchar(255) DEFAULT NULL,
  `PREZZO` tinyint(4) DEFAULT NULL,
  `COPERTO` tinyint(1) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `LINK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `PARTECIPAZIONE`;
CREATE TABLE IF NOT EXISTS `PARTECIPAZIONE` (
  `USER_ID` varchar(30) NOT NULL DEFAULT '',
  `ID_PARTITA` int(11) NOT NULL DEFAULT '0',
  `PARTECIPA` smallint(6) DEFAULT '0',
  `SOMMAVOTI` float DEFAULT '0',
  `NUMVOTANTI` tinyint(4) DEFAULT '0',
  `VOTATO` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`USER_ID`,`ID_PARTITA`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `PARTITA`;
CREATE TABLE IF NOT EXISTS `PARTITA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CAMPO` tinyint(4) DEFAULT NULL,
  `ORA_INIZIO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_ORGANIZZATORE` varchar(30) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  `STATO` varchar(1) DEFAULT 'A',
  PRIMARY KEY (`ID`),
  FULLTEXT KEY `ID_ORGANIZZATORE` (`ID_ORGANIZZATORE`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `TZ_MEMBERS`;
CREATE TABLE IF NOT EXISTS `TZ_MEMBERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SURNAME` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `USR` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `PASS` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `EMAIL` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ACCEPT` tinyint(1) DEFAULT '0',
  `LEVEL` tinyint(1) NOT NULL DEFAULT '0',
  `REGIP` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MOBILE` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `usr` (`USR`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

